Repository openshift/cluster-machine-approver, pull requests merged in 2019-09, with the labels that each got.

#41 Increase the CSR retry count to 30
  main.go
Labels: approved, lgtm, size/XS

#44 Add consumer given values to logs
  csr_check.go
  csr_check_test.go
Labels: approved, lgtm, size/M

#45 Extend makefile with 'make goimports' target
  Makefile
  hack/goimports.sh
Labels: approved, lgtm, size/S

#43 Increase pending allowed
  csr_check_test.go
  main.go
Labels: approved, lgtm, size/M

#38 Bug 1737611: Simplified approval flow for renewing serving certs
  csr_check.go
  csr_check_test.go
  main.go
  manifests/01-rbac.yaml
  manifests/01-sa.yaml
  manifests/02-clusterrole.yaml
  manifests/02-deployment.yaml
  manifests/03-clusterrolebinding.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#47 Add more logging for failed isReqFromNodeBootstrapper
  csr_check.go
  csr_check_test.go
Labels: approved, lgtm, size/XS
