Repository openshift/cluster-machine-approver, pull requests merged in 2019-12, with the labels that each got.

#57 Bug 1779107: Fall back to machine-api check if certificate check fails
  csr_check.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#61 Fix IPv6 connections in getServingCert
  csr_check.go
  csr_check_test.go
Labels: approved, lgtm, size/S

#60 Add resource request to container
  manifests/04-deployment.yaml
Labels: approved, lgtm, size/XS

#59 [release-4.2] Bug 1781160: Fall back to machine-api check if certificate check fails
  csr_check.go
  csr_check_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L
