Repository openshift/cluster-machine-approver, pull requests merged in 2020-09, with the labels that each got.

#83 Bug 1872080: Create Dockerfile.rhel file
  Dockerfile.rhel
  Dockerfile.rhel7
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#84 Bug 1875036: Remove deprecated Dockerfile.rhel7 file
  Dockerfile.rhel7
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#85 Bug 1879159: stop communicating with Kube API via localhost
  manifests/04-deployment.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#89 Bug 1883497: Fix missing logs due to mixed klog versions
  config.go
  csr_check.go
  go.mod
  main.go
  metrics.go
  status.go
  status_suite_test.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/v2/klogr/README.md
  vendor/k8s.io/klog/v2/klogr/klogr.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
