Repository openshift/cluster-machine-approver, pull requests merged in 2021-11, with the labels that each got.

#139 Bug 2019754: Ensure pending CSR count is valid post approval
  pkg/controller/controller.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#141 Bug 2024216: Allow fallback to serving cert renewal accounting for egress IPs on SDN
  main.go
  manifests/01-rbac.yaml
  pkg/controller/csr_check.go
  pkg/controller/csr_check_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#138 Bug 2010359: add summary and description to alerts
  manifests/0000_90_cluster-machine-approver_04_alertrules.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low
