Repository openshift/cluster-machine-approver, pull requests merged in 2021-04, with the labels that each got.

#107 Enable running make targets inside container
  Makefile
  hack/go-mod.sh
  hack/goimports.sh
  hack/imagebuilder.sh
Labels: approved, lgtm

#93 Add IBM Cloud managed annotations to CVO manifests
  manifests/00-ns.yaml
  manifests/0000_90_cluster-machine-approver_01_prometheusrole.yaml
  manifests/0000_90_cluster-machine-approver_02_prometheusrolebinding.yaml
  manifests/0000_90_cluster-machine-approver_03_servicemonitor.yaml
  manifests/01-rbac.yaml
  manifests/02-kube-rbac-proxy-config.yaml
  manifests/03-metrics-service.yaml
Labels: approved, lgtm

#111 Bug 1947785: Move certificates to v1
  go.sum
  pkg/controller/controller.go
  pkg/controller/csr_check.go
  pkg/controller/csr_check_test.go
  pkg/controller/node_client.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#113 Bug 1949741: bump golang versions
  Dockerfile
  Dockerfile.rhel
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#117 Bug 1940972: Increase cache resync period to 10 min instead of 10 hours
  main.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#118 Bug 1952282: Ensure serving certs requeued
  pkg/controller/csr_check.go
  pkg/controller/csr_check_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#110 Add management workload annotations
  manifests/00-ns.yaml
  manifests/04-deployment.yaml
Labels: approved, backports/validated-commits, bugzilla/valid-bug, lgtm
