Repository openshift/cluster-machine-approver, pull requests merged in 2022-03, with the labels that each got.

#158 Bug 1978303: update approve condition logic
  pkg/controller/controller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#159 Add techpreview manifests for CAPI machines
  manifests/01-rbac-capi.yaml
  manifests/04-deployment-capi.yaml
Labels: approved, lgtm

#160 Bug 2047702: Reconcile CSRs approved by other controllers
  pkg/controller/controller.go
  pkg/controller/csr_check.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
