Repository openshift/cluster-machine-approver, pull requests merged in 2024-12, with the labels that each got.

#248 OCPBUGS-45306: Client internal DNS checks should ignore trailing dot
  pkg/controller/csr_check_test.go
  pkg/machinehandler/machinehandler.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference, acknowledge-critical-fixes-only

#253 OCPBUGS-45306: Ensure trailing dots on DNS names do not block serving cert auth
  pkg/controller/csr_check.go
  pkg/controller/csr_check_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#243 OCPBUGS-36404: Filter CSRs by signerName
  main.go
  pkg/controller/controller.go
  pkg/controller/csr_check.go
  pkg/controller/csr_check_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#262 OCPCLOUD-2787: Deploy CAPI manifests in CustomNoUpgrade
  manifests/01-rbac-capi.yaml
  manifests/04-deployment-capi.yaml
Labels: approved, lgtm, jira/valid-reference
